# Generated by Django 2.2.17 on 2020-11-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='title',
            new_name='hgjghjhjgjgjh',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='hgfhfgfhgfhgfhgf',
        ),
    ]
